# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

downInPrice <- function(nInt, strike, spot, vol, r, expiry, barrier, reps) {
    .Call(`_PackageProject_downInPrice`, nInt, strike, spot, vol, r, expiry, barrier, reps)
}

rcpp_hello_world <- function() {
    .Call(`_PackageProject_rcpp_hello_world`)
}

